model_config: 
    loss : physioex.train.networks.utils.loss:CrossEntropyLoss
    loss_kwargs : {}
    sequence_length: 19
    n_classes: 5
    in_channels: 1
    sf: 100
    n_times: 3000
    learning_rate: 1e-3
    weight_decay: 1e-4
    adam_beta_1: 0.9
    adam_beta_2: 0.999
    adam_epsilon: 1e-8
    latent_space_dim: 32
    input_processing : raw
    batch_size: 128
checkpoint_path : "./model/checkpoint/"
input_transform: "raw"
model: physioex.train.networks.chambon2018:Chambon2018Net
model_name: "chambon2018"
module: physioex.train.networks:Chambon2018Net
preprocessing : raw
target_transform: physioex.train.networks.utils.target_transform:get_mid_label
