config: &id001
  adam_beta_1: 0.9
  adam_beta_2: 0.999
  adam_epsilon: 1.0e-08
  batch_size: 128
  in_channels: 1
  input_processing: raw
  latent_space_dim: 32
  learning_rate: 0.001
  loss: physioex.train.networks.utils.loss:CrossEntropyLoss
  loss_kwargs: {}
  n_classes: 5
  n_times: 3000
  sequence_length: 19
  sf: 100
  weight_decay: 0.0001
module_config: *id001
